---
name: build and push docker image
on:
  push

jobs:
  register:
    name: Package, Publish, and Register
    runs-on:
    - ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}
    - name: Get git sha short
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - id: setup-pack
      uses: buildpacks/github-actions/setup-pack@v4.4.0
    - id: package
      run: |
        #!/usr/bin/env bash
        set -euo pipefail
        BP_ID="heroku/python"
        VERSION="0.3.1"
        PACKAGE="${REPO}/$(echo "$BP_ID" | sed 's/\//_/g')"
        pack build --path .  --builder heroku/buildpacks:20 --publish ${REPO}/cnb:sha-${{ steps.vars.outputs.sha_short }}
        pack buildpack package --publish ${PACKAGE}:${VERSION}
        DIGEST="$(crane digest ${PACKAGE}:${VERSION})"
        echo "::set-output name=bp_id::$BP_ID"
        echo "::set-output name=version::$VERSION"
        echo "::set-output name=address::${PACKAGE}@${DIGEST}"        
      shell: bash
      env:
        REPO: docker.io/${{ secrets.DOCKER_HUB_USER }}
    - id: register
      uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:4.4.0
      with:
        token:   ${{ secrets.PUBLIC_REPO_TOKEN }}
        id:      ${{ steps.package.outputs.bp_id }}
        version: ${{ steps.package.outputs.version }}
        address: ${{ steps.package.outputs.address }}


        
    - name: Generate deploy manifest from Jinja template
      uses: cuchi/jinja2-action@v1.1.0
      with: 
        template: tmpl/hello.j2
        output_file: deploy/hello.yaml
        strict: true
        variables: |
          image_deploy_tag=sha-${{ steps.vars.outputs.sha_short }}
            
    - name: Commit deploy manifest on local repo
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -s -m "[skip ci] Generate deployment manifests" 
          
    - name: Push deploy manifests to local repo
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{ secrets.AUTO_COMMIT_TOKEN }}            
